from molop import AutoParser
import numpy as np
from rdkit import Chem
pt = Chem.GetPeriodicTable()
def symbol_pos_to_xyz_file(symbols,positions,xyz_file,title=""):
    with open(xyz_file, 'w') as f:
        f.write(f"{len(symbols)}\n")
        f.write(f"{title}\n")
        for symbol, pos in zip(symbols, positions):
            f.write(f"{symbol:4s} {pos[0]:15f} {pos[1]:15f} {pos[2]:15f}\n")

def generate_g16_input_file(gjf_file,atoms,coords,charge,multiplicity,method,jobtype,cpu,memory):
    information = [
    f'%nproc={cpu}',
    f'%mem={memory}GB',
    f'# {jobtype} {method}',
    "",
    "Generated by QuantumCalcAgent",
    "",
    f"{charge} {multiplicity}",
    ]
    for atom, coord in zip(atoms, coords):
        information.append(f"{atom:5s} {coord[0]:15f} {coord[1]:15f} {coord[2]:15f}")
        
    information += ["",""]
    with open(gjf_file, 'w') as f:
        f.write("\n".join(information))

def molop_parser(xyz_file):
    parser_mol = AutoParser(xyz_file)[0][-1]
    rdmol = parser_mol.rdmol
    charge = parser_mol.charge
    multiplicity = parser_mol.multiplicity
    coords = np.array(parser_mol.coords)
    atoms = [pt.GetElementSymbol(atom) for atom in parser_mol.atoms]
    return atoms,coords,charge,multiplicity
